# Generated by Django 4.2.3 on 2024-09-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userext',
            name='user',
        ),
        migrations.DeleteModel(
            name='BoardRole',
        ),
        migrations.DeleteModel(
            name='UserExt',
        ),
    ]
